// This was created by taking the initial data out of Chrome/111.0.0.0 and transforming it
export type YouTubeConfig = Partial<{
    CLIENT_CANARY_STATE: string
    DEVICE: string
    DISABLE_YT_IMG_DELAY_LOADING: boolean
    ELEMENT_POOL_DEFAULT_CAP: number
    EVENT_ID: string
    EXPERIMENT_FLAGS: {
        H5_enable_full_pacf_logging: boolean
        H5_use_async_logging: boolean
        allow_skip_networkless: boolean
        autoescape_tempdata_url: boolean
        background_thread_flush_logs_due_to_batch_limit: boolean
        browse_next_continuations_migration_playlist: boolean
        c3_watch_page_component: boolean
        cache_utc_offset_minutes_in_pref_cookie: boolean
        cancel_pending_navs: boolean
        check_user_lact_at_prompt_shown_time_on_web: boolean
        clear_user_partitioned_ls: boolean
        client_respect_autoplay_switch_button_renderer: boolean
        cold_missing_history: boolean
        csi_on_gel: boolean
        decorate_autoplay_renderer: boolean
        defer_menus: boolean
        defer_overlays: boolean
        defer_rendering_outside_visible_area: boolean
        deprecate_csi_has_info: boolean
        deprecate_pair_servlet_enabled: boolean
        deprecate_two_way_binding_child: boolean
        deprecate_two_way_binding_parent: boolean
        desktop_add_to_playlist_renderer_dialog_popup: boolean
        desktop_adjust_touch_target: boolean
        desktop_animate_miniplayer: boolean
        desktop_client_release: boolean
        desktop_delay_player_resizing: boolean
        desktop_enable_dmpanel_click_drag_scroll: boolean
        desktop_enable_dmpanel_scroll: boolean
        desktop_enable_dmpanel_wheel_scroll: boolean
        desktop_image_cta_no_background: boolean
        desktop_keyboard_capture_keydown_killswitch: boolean
        desktop_log_img_click_location: boolean
        desktop_mix_use_sampled_color_for_bottom_bar: boolean
        desktop_mix_use_sampled_color_for_bottom_bar_search: boolean
        desktop_mix_use_sampled_color_for_bottom_bar_watch_next: boolean
        desktop_notification_high_priority_ignore_push: boolean
        desktop_notification_set_title_bar: boolean
        desktop_persistent_menu: boolean
        desktop_search_prominent_thumbs: boolean
        desktop_sparkles_light_cta_button: boolean
        desktop_swipeable_guide: boolean
        desktop_themeable_vulcan: boolean
        desktop_touch_gestures_usage_log: boolean
        desktop_use_new_history_manager: boolean
        disable_child_node_auto_formatted_strings: boolean
        disable_dependency_injection: boolean
        disable_exif_rotation_for_image_posts: boolean
        disable_features_for_supex: boolean
        disable_legacy_desktop_remote_queue: boolean
        disable_pacf_logging_for_memory_limited_tv: boolean
        disable_simple_mixed_direction_formatted_strings: boolean
        disable_thumbnail_preloading: boolean
        embeds_web_enable_replace_unload_w_pagehide: boolean
        embeds_web_enable_watch_on_autoplay: boolean
        embeds_web_nwl_disable_nocookie: boolean
        enable_audio_pivot_back_nav_button: boolean
        enable_button_behavior_reuse: boolean
        enable_call_to_action_clarification_renderer_bottom_section_conditions: boolean
        enable_client_sli_logging: boolean
        enable_client_streamz_web: boolean
        enable_commerce_action_request_sequencing: boolean
        enable_desktop_amsterdam_info_panels: boolean
        enable_docked_chat_messages: boolean
        enable_gel_log_commands: boolean
        enable_get_account_switcher_endpoint_on_webfe: boolean
        enable_handles_account_menu_switcher: boolean
        enable_handles_in_mention_suggest_posts: boolean
        enable_handoff_location_2fa_on_mweb: boolean
        enable_header_channel_handler_ui: boolean
        enable_hlp_client_icon_pick: boolean
        enable_image_poll_post_creation: boolean
        enable_inline_preview_controls: boolean
        enable_inline_shorts_on_wn: boolean
        enable_madison_search_migration: boolean
        enable_masthead_quartile_ping_fix: boolean
        enable_memberships_and_purchases: boolean
        enable_mentions_in_reposts: boolean
        enable_microformat_data: boolean
        enable_mini_app_container: boolean
        enable_mixed_direction_formatted_strings: boolean
        enable_multi_image_post_creation: boolean
        enable_names_handles_account_switcher: boolean
        enable_offer_suppression: boolean
        enable_on_yt_command_executor_command_to_navigate: boolean
        enable_pacf_through_ysfe_tv: boolean
        enable_poll_choice_border_on_web: boolean
        enable_polymer_resin: boolean
        enable_polymer_resin_migration: boolean
        enable_post_cct_links: boolean
        enable_post_scheduling: boolean
        enable_premium_voluntary_pause: boolean
        enable_programmed_playlist_color_sample: boolean
        enable_programmed_playlist_redesign: boolean
        enable_purchase_activity_in_paid_memberships: boolean
        enable_reel_watch_sequence: boolean
        enable_rejected_sasde_for_html5: boolean
        enable_rendererstamper_listener_cleanup: boolean
        enable_seedless_shorts_url: boolean
        enable_server_stitched_dai: boolean
        enable_service_ajax_csn: boolean
        enable_servlet_errors_streamz: boolean
        enable_servlet_streamz: boolean
        enable_sfv_audio_pivot_url: boolean
        enable_shorts_on_library: boolean
        enable_shorts_singleton_channel_web: boolean
        enable_signals: boolean
        enable_skip_ad_guidance_prompt: boolean
        enable_skippable_ads_for_unplugged_ad_pod: boolean
        enable_smearing_expansion_dai: boolean
        enable_squiffle_gif_handles_landing_page: boolean
        enable_streamline_repost_flow: boolean
        enable_structured_description_shorts_web_mweb: boolean
        enable_tectonic_ad_ux_for_halftime: boolean
        enable_third_party_info: boolean
        enable_topsoil_wta_for_halftime_live_infra: boolean
        enable_unavailable_videos_watch_page: boolean
        enable_unified_show_page_web_client: boolean
        enable_watch_next_pause_autoplay_lact: boolean
        enable_web_ketchup_hero_animation: boolean
        enable_web_poster_hover_animation: boolean
        enable_web_scheduler_signals: boolean
        enable_web_shorts_audio_pivot: boolean
        enable_yoodle: boolean
        enable_ypc_spinners: boolean
        enable_yt_ata_iframe_authuser: boolean
        enable_ytc_refunds_submit_form_signal_action: boolean
        enable_ytc_self_serve_refunds: boolean
        endpoint_handler_logging_cleanup_killswitch: boolean
        export_networkless_options: boolean
        external_fullscreen: boolean
        external_fullscreen_with_edu: boolean
        fill_single_video_with_notify_to_lasr: boolean
        gcf_config_store_enabled: boolean
        gda_enable_playlist_download: boolean
        gfeedback_for_signed_out_users_enabled: boolean
        global_spacebar_pause: boolean
        gpa_sparkles_ten_percent_layer: boolean
        h5_companion_enable_adcpn_macro_substitution_for_click_pings: boolean
        h5_inplayer_enable_adcpn_macro_substitution_for_click_pings: boolean
        hide_endpoint_overflow_on_ytd_display_ad_renderer: boolean
        html5_enable_ads_client_monitoring_log_tv: boolean
        html5_enable_single_video_vod_ivar_on_pacf: boolean
        html5_log_trigger_events_with_debug_data: boolean
        html5_recognize_predict_start_cue_point: boolean
        html5_server_stitched_dai_group: boolean
        html5_web_enable_halftime_preroll: boolean
        il_use_view_model_logging_context: boolean
        include_autoplay_count_in_playlists: boolean
        is_browser_support_for_webcam_streaming: boolean
        is_part_of_any_user_engagement_experiment: boolean
        json_condensed_response: boolean
        kevlar_app_shortcuts: boolean
        kevlar_appbehavior_attach_startup_tasks: boolean
        kevlar_append_toggled_engagement_panels_top: boolean
        kevlar_appshell_service_worker: boolean
        kevlar_autofocus_menu_on_keyboard_nav: boolean
        kevlar_autonav_popup_filtering: boolean
        kevlar_av_eliminate_polling: boolean
        kevlar_background_color_update: boolean
        kevlar_cache_cold_load_response: boolean
        kevlar_cache_on_ttl_player: boolean
        kevlar_cache_on_ttl_search: boolean
        kevlar_calculate_grid_collapsible: boolean
        kevlar_cancel_scheduled_comment_jobs_on_navigate: boolean
        kevlar_center_search_results: boolean
        kevlar_channel_creation_form_resolver: boolean
        kevlar_channel_trailer_multi_attach: boolean
        kevlar_chapters_list_view_seek_by_chapter: boolean
        kevlar_clear_duplicate_pref_cookie: boolean
        kevlar_clear_non_displayable_url_params: boolean
        kevlar_client_side_screens: boolean
        kevlar_command_handler: boolean
        kevlar_command_handler_clicks: boolean
        kevlar_command_handler_formatted_string: boolean
        kevlar_command_url: boolean
        kevlar_continue_playback_without_player_response: boolean
        kevlar_decorate_endpoint_with_onesie_config: boolean
        kevlar_delay_watch_initial_data: boolean
        kevlar_disable_background_prefetch: boolean
        kevlar_disable_pending_command: boolean
        kevlar_downloads_on_home: boolean
        kevlar_dragdrop_fast_scroll: boolean
        kevlar_dropdown_fix: boolean
        kevlar_droppable_prefetchable_requests: boolean
        kevlar_early_popup_close: boolean
        kevlar_enable_download_upsell_type_a: boolean
        kevlar_enable_editable_playlists: boolean
        kevlar_enable_reorderable_playlists: boolean
        kevlar_enable_shorts_prefetch_in_sequence: boolean
        kevlar_enable_shorts_response_chunking: boolean
        kevlar_enable_up_arrow: boolean
        kevlar_enable_upsell_on_video_menu: boolean
        kevlar_enable_ybp_op_for_shoptube: boolean
        kevlar_exit_fullscreen_leaving_watch: boolean
        kevlar_fix_playlist_continuation: boolean
        kevlar_flexible_menu: boolean
        kevlar_fluid_touch_scroll: boolean
        kevlar_frontend_queue_recover: boolean
        kevlar_gel_error_routing: boolean
        kevlar_guide_refresh: boolean
        kevlar_help_use_locale: boolean
        kevlar_hide_playlist_playback_status: boolean
        kevlar_hide_pp_url_param: boolean
        kevlar_hide_time_continue_url_param: boolean
        kevlar_home_skeleton: boolean
        kevlar_home_skeleton_hide_later: boolean
        kevlar_js_fixes: boolean
        kevlar_keyboard_button_focus: boolean
        kevlar_larger_three_dot_tap: boolean
        kevlar_lazy_list_resume_for_autofill: boolean
        kevlar_live_report_menu_item: boolean
        kevlar_local_innertube_response: boolean
        kevlar_macro_markers_keyboard_shortcut: boolean
        kevlar_masthead_store: boolean
        kevlar_mealbar_above_player: boolean
        kevlar_miniplayer: boolean
        kevlar_miniplayer_expand_top: boolean
        kevlar_miniplayer_play_pause_on_scrim: boolean
        kevlar_miniplayer_queue_user_activation: boolean
        kevlar_mix_handle_first_endpoint_different: boolean
        kevlar_modern_sd: boolean
        kevlar_network_banner: boolean
        kevlar_next_cold_on_auth_change_detected: boolean
        kevlar_nitrate_driven_tooltips: boolean
        kevlar_no_autoscroll_on_playlist_hover: boolean
        kevlar_op_infra: boolean
        kevlar_op_warm_pages: boolean
        kevlar_pandown_polyfill: boolean
        kevlar_passive_event_listeners: boolean
        kevlar_playback_associated_queue: boolean
        kevlar_player_cached_load_config: boolean
        kevlar_player_check_ad_state_on_stop: boolean
        kevlar_player_load_player_no_op: boolean
        kevlar_player_new_bootstrap_adoption: boolean
        kevlar_player_playlist_use_local_index: boolean
        kevlar_player_watch_endpoint_navigation: boolean
        kevlar_playlist_drag_handles: boolean
        kevlar_playlist_responsive: boolean
        kevlar_playlist_use_x_close_button: boolean
        kevlar_prefetch: boolean
        kevlar_prevent_polymer_dynamic_font_load: boolean
        kevlar_queue_use_update_api: boolean
        kevlar_refresh_gesture: boolean
        kevlar_refresh_on_theme_change: boolean
        kevlar_rendererstamper_event_listener: boolean
        kevlar_replace_short_to_short_history_state: boolean
        kevlar_request_sequencing: boolean
        kevlar_resolve_command_for_confirm_dialog: boolean
        kevlar_resolve_playlist_endpoint_as_watch_endpoint: boolean
        kevlar_response_command_processor_page: boolean
        kevlar_run_attestation_fix_killswitch: boolean
        kevlar_scroll_chips_on_touch: boolean
        kevlar_scrollbar_rework: boolean
        kevlar_service_command_check: boolean
        kevlar_set_internal_player_size: boolean
        kevlar_set_sd_enabled_browse_request: boolean
        kevlar_shell_for_downloads_page: boolean
        kevlar_should_maintain_stable_list: boolean
        kevlar_smart_downloads: boolean
        kevlar_smart_downloads_setting: boolean
        kevlar_startup_lifecycle: boolean
        kevlar_structured_description_content_inline: boolean
        kevlar_system_icons: boolean
        kevlar_tabs_gesture: boolean
        kevlar_text_inline_expander_formatted_snippet: boolean
        kevlar_three_dot_ink: boolean
        kevlar_thumbnail_fluid: boolean
        kevlar_toast_manager: boolean
        kevlar_topbar_logo_fallback_home: boolean
        kevlar_touch_feedback: boolean
        kevlar_touch_feedback_lockups: boolean
        kevlar_touch_gesture_ves: boolean
        kevlar_transcript_engagement_panel: boolean
        kevlar_tuner_run_default_comments_delay: boolean
        kevlar_tuner_should_defer_detach: boolean
        kevlar_typography_spacing_update: boolean
        kevlar_typography_update: boolean
        kevlar_unavailable_video_error_ui_client: boolean
        kevlar_unified_errors_init: boolean
        kevlar_use_response_ttl_to_invalidate_cache: boolean
        kevlar_use_vimio_behavior: boolean
        kevlar_use_ytd_player: boolean
        kevlar_variable_youtube_sans: boolean
        kevlar_vimio_use_shared_monitor: boolean
        kevlar_voice_logging_fix: boolean
        kevlar_voice_search: boolean
        kevlar_watch_cinematics: boolean
        kevlar_watch_color_update: boolean
        kevlar_watch_comments_ep_disable_theater: boolean
        kevlar_watch_drag_handles: boolean
        kevlar_watch_flexy_autonav_manager: boolean
        kevlar_watch_flexy_use_controller: boolean
        kevlar_watch_focus_on_engagement_panels: boolean
        kevlar_watch_gesture_pandown: boolean
        kevlar_watch_hide_comments_teaser: boolean
        kevlar_watch_hide_comments_while_panel_open: boolean
        kevlar_watch_js_panel_height: boolean
        kevlar_watch_metadata_refresh: boolean
        kevlar_watch_metadata_refresh_attached_subscribe: boolean
        kevlar_watch_metadata_refresh_clickable_description: boolean
        kevlar_watch_metadata_refresh_compact_view_count: boolean
        kevlar_watch_metadata_refresh_description_info_dedicated_line: boolean
        kevlar_watch_metadata_refresh_description_inline_expander: boolean
        kevlar_watch_metadata_refresh_description_primary_color: boolean
        kevlar_watch_metadata_refresh_for_live_killswitch: boolean
        kevlar_watch_metadata_refresh_full_width_description: boolean
        kevlar_watch_metadata_refresh_left_aligned_video_actions: boolean
        kevlar_watch_metadata_refresh_lower_case_video_actions: boolean
        kevlar_watch_metadata_refresh_narrower_item_wrap: boolean
        kevlar_watch_metadata_refresh_relative_date: boolean
        kevlar_watch_metadata_refresh_top_aligned_actions: boolean
        kevlar_watch_modern_metapanel: boolean
        kevlar_watch_modern_panels: boolean
        kevlar_watch_panel_height_matches_player: boolean
        kevlar_woffle: boolean
        kevlar_woffle_fallback_image: boolean
        kevlar_ytb_live_badges: boolean
        killswitch_toggle_button_behavior_resolve_command: boolean
        live_chat_banner_expansion_fix: boolean
        live_chat_collapse_merch_banner: boolean
        live_chat_enable_mod_view: boolean
        live_chat_enable_qna_banner_overflow_menu_actions: boolean
        live_chat_enable_qna_channel: boolean
        live_chat_increased_min_height: boolean
        live_chat_over_playlist: boolean
        log_errors_through_nwl_on_retry: boolean
        log_heartbeat_with_lifecycles: boolean
        log_vis_on_tab_change: boolean
        log_web_endpoint_to_layer: boolean
        mdx_enable_privacy_disclosure_ui: boolean
        mdx_load_cast_api_bootstrap_script: boolean
        migrate_events_to_ts: boolean
        music_on_main_handle_playlist_edit_video_added_result_data: boolean
        mweb_actions_command_handler: boolean
        mweb_command_handler: boolean
        mweb_disable_set_autonav_state_in_player: boolean
        mweb_enable_consistency_service: boolean
        mweb_enable_hlp: boolean
        mweb_enable_rounded_searchbox: boolean
        mweb_logo_use_home_page_ve: boolean
        mweb_navigate_to_watch_with_op: boolean
        networkless_gel: boolean
        networkless_logging: boolean
        no_sub_count_on_sub_button: boolean
        nwl_send_fast_on_unload: boolean
        nwl_send_from_memory_when_online: boolean
        offline_error_handling: boolean
        pageid_as_header_web: boolean
        parse_query_data_from_url: boolean
        pause_ad_video_on_desktop_engagement_panel_click: boolean
        pdg_enable_flow_logging_for_super_chat: boolean
        pdg_enable_flow_logging_for_super_stickers: boolean
        player_allow_autonav_after_playlist: boolean
        player_bootstrap_method: boolean
        player_doubletap_to_seek: boolean
        player_enable_playback_playlist_change: boolean
        player_endscreen_ellipsis_fix: boolean
        polymer_bad_build_labels: boolean
        polymer_task_manager_proxied_promise: boolean
        polymer_verifiy_app_state: boolean
        polymer_video_renderer_defer_menu: boolean
        polymer_warm_thumbnail_preload: boolean
        polymer_ytdi_enable_global_injector: boolean
        problem_walkthrough_sd: boolean
        qoe_send_and_write: boolean
        record_app_crashed_web: boolean
        reload_without_polymer_innertube: boolean
        remove_web_comment_id_cache: boolean
        remove_yt_simple_endpoint_from_desktop_display_ad_title: boolean
        rich_grid_browse_compute_kill_switch: boolean
        rich_grid_mini_mode: boolean
        rich_grid_watch_meta_side: boolean
        rich_grid_watch_show_watch_next: boolean
        scheduler_use_raf_by_default: boolean
        search_ui_enable_pve_buy_button: boolean
        search_ui_official_cards_enable_paid_virtual_event_buy_button: boolean
        searchbox_reporting: boolean
        serve_pdp_at_canonical_url: boolean
        service_worker_enabled: boolean
        service_worker_push_enabled: boolean
        service_worker_push_home_page_prompt: boolean
        service_worker_push_watch_page_prompt: boolean
        service_worker_subscribe_with_vapid_key: boolean
        shorts_enable_snap_stop: boolean
        should_clear_video_data_on_player_cued_unstarted: boolean
        show_civ_reminder_on_web: boolean
        skip_invalid_ytcsi_ticks: boolean
        skip_ls_gel_retry: boolean
        skip_setting_info_in_csi_data_object: boolean
        sponsorships_gifting_enable_opt_in: boolean
        start_client_gcf: boolean
        start_client_gcf_for_player: boolean
        super_sticker_emoji_picker_category_button_icon_filled: boolean
        suppress_error_204_logging: boolean
        track_webfe_innertube_auth_mismatch: boolean
        transport_use_scheduler: boolean
        use_ads_engagement_panel_desktop_footer_cta: boolean
        use_better_post_dismissals: boolean
        use_border_and_grid_wrapping_on_desktop_panel_tiles: boolean
        use_new_in_memory_storage: boolean
        use_new_nwl_initialization: boolean
        use_new_nwl_saw: boolean
        use_new_nwl_stw: boolean
        use_new_nwl_wts: boolean
        use_player_abuse_bg_library: boolean
        use_profilepage_event_label_in_carousel_playbacks: boolean
        use_request_time_ms_header: boolean
        use_session_based_sampling: boolean
        use_shared_nsm: boolean
        use_shared_nsm_and_keep_yt_online_updated: boolean
        use_source_element_if_present_for_actions: boolean
        use_ts_visibilitylogger: boolean
        use_watch_fragments2: boolean
        verify_ads_itag_early: boolean
        vss_final_ping_send_and_write: boolean
        vss_playback_use_send_and_write: boolean
        warm_load_nav_start_web: boolean
        warm_op_csn_cleanup: boolean
        web_always_load_chat_support: boolean
        web_amsterdam_playlists: boolean
        web_amsterdam_post_mvp_playlists: boolean
        web_animated_like: boolean
        web_animated_like_lazy_load: boolean
        web_api_url: boolean
        web_appshell_purge_trigger: boolean
        web_appshell_refresh_trigger: boolean
        web_autonav_allow_off_by_default: boolean
        web_button_rework: boolean
        web_darker_dark_theme: boolean
        web_darker_dark_theme_deprecate: boolean
        web_dedupe_ve_grafting: boolean
        web_defer_shorts_ui: boolean
        web_defer_shorts_ui_phase2: boolean
        web_deprecate_service_ajax_map_dependency: boolean
        web_enable_history_cache_map: boolean
        web_enable_video_preview_migration: boolean
        web_enable_voz_audio_feedback: boolean
        web_engagement_panel_show_description: boolean
        web_ep_chevron_tap_target_size: boolean
        web_filled_subscribed_button: boolean
        web_forward_command_on_pbj: boolean
        web_gel_timeout_cap: boolean
        web_guide_ui_refresh: boolean
        web_hide_autonav_headline: boolean
        web_hide_autonav_keyline: boolean
        web_inline_player_enabled: boolean
        web_kevlar_enable_adaptive_signals: boolean
        web_log_memory_total_kbytes: boolean
        web_log_player_watch_next_ticks: boolean
        web_log_reels_ticks: boolean
        web_modern_ads: boolean
        web_modern_buttons: boolean
        web_modern_buttons_bl_survey: boolean
        web_modern_chips: boolean
        web_modern_dialogs: boolean
        web_modern_playlists: boolean
        web_modern_subscribe: boolean
        web_move_autoplay_video_under_chip: boolean
        web_moved_super_title_link: boolean
        web_one_platform_error_handling: boolean
        web_paused_only_miniplayer_shortcut_expand: boolean
        web_player_autonav_empty_suggestions_fix: boolean
        web_player_autonav_toggle_always_listen: boolean
        web_player_autonav_use_server_provided_state: boolean
        web_player_decouple_autonav: boolean
        web_player_disable_inline_scrubbing: boolean
        web_player_enable_early_warning_snackbar: boolean
        web_player_enable_ipp: boolean
        web_player_enable_premium_hbr_in_h5_api: boolean
        web_player_enable_premium_hbr_playback_cap: boolean
        web_player_entities_middleware: boolean
        web_player_move_autonav_toggle: boolean
        web_player_mutable_event_label: boolean
        web_player_should_honor_include_asr_setting: boolean
        web_player_small_hbp_settings_menu: boolean
        web_player_touch_mode_improvements: boolean
        web_player_use_new_api_for_quality_pullback: boolean
        web_player_watch_next_response: boolean
        web_prefetch_preload_video: boolean
        web_prs_testing_mode_killswitch: boolean
        web_replace_thumbnail_with_image: boolean
        web_rounded_containers: boolean
        web_rounded_thumbnails: boolean
        web_search_inline_playback_mouse_enter: boolean
        web_segmented_like_dislike_button: boolean
        web_sheets_ui_refresh: boolean
        web_shorts_early_player_load: boolean
        web_shorts_progress_bar: boolean
        web_shorts_shelf_on_search: boolean
        web_shorts_skip_loading_same_index: boolean
        web_snackbar_ui_refresh: boolean
        web_structured_description_show_more: boolean
        web_use_cache_for_image_fallback: boolean
        web_yt_config_context: boolean
        woffle_clean_up_after_entity_migration: boolean
        woffle_enable_download_status: boolean
        woffle_orchestration: boolean
        your_data_entrypoint: boolean
        yt_network_manager_component_to_lib_killswitch: boolean
        ytidb_clear_embedded_player: boolean
        ytidb_fetch_datasync_ids_for_data_cleanup: boolean
        H5_async_logging_delay_ms: number
        addto_ajax_log_warning_fraction: number
        autoplay_pause_by_lact_sampling_fraction: number
        browse_ajax_log_warning_fraction: number
        cinematic_watch_effect_opacity: number
        formatted_description_log_warning_fraction: number
        kevlar_tuner_clamp_device_pixel_ratio: number
        kevlar_tuner_thumbnail_factor: number
        kevlar_unified_player_logging_threshold: number
        log_window_onerror_fraction: number
        polymer_report_client_url_requested_rate: number
        polymer_report_missing_web_navigation_endpoint_rate: number
        prefetch_coordinator_error_logging_sampling_rate: number
        tv_pacf_logging_sample_rate: number
        web_shorts_error_logging_threshold: number
        web_shorts_intersection_observer_threshold_override: number
        web_system_health_fraction: number
        ytidb_transaction_ended_event_rate_limit: number
        ytidb_transaction_ended_event_rate_limit_session: number
        ytidb_transaction_ended_event_rate_limit_transaction: number
        autoplay_pause_by_lact_sec: number
        autoplay_time: number
        autoplay_time_for_fullscreen: number
        autoplay_time_for_music_content: number
        botguard_async_snapshot_timeout_ms: number
        check_navigator_accuracy_timeout_ms: number
        cinematic_watch_css_filter_blur_strength: number
        cinematic_watch_fade_out_duration: number
        client_streamz_web_flush_count: number
        client_streamz_web_flush_interval_seconds: number
        compression_disable_point: number
        compression_performance_threshold: number
        desktop_search_suggestion_tap_target: number
        external_fullscreen_button_click_threshold: number
        external_fullscreen_button_shown_threshold: number
        gel_queue_timeout_max_ms: number
        get_async_timeout_ms: number
        high_priority_flyout_frequency: number
        initial_gel_batch_timeout: number
        kevlar_mini_guide_width_threshold: number
        kevlar_persistent_guide_width_threshold: number
        kevlar_time_caching_end_threshold: number
        kevlar_time_caching_start_threshold: number
        kevlar_tooltip_impression_cap: number
        kevlar_tuner_default_comments_delay: number
        kevlar_tuner_scheduler_soft_state_timer_ms: number
        kevlar_tuner_visibility_time_between_jobs_ms: number
        kevlar_watch_flexy_metadata_height: number
        kevlar_watch_metadata_refresh_description_lines: number
        live_chat_chunk_rendering: number
        live_chat_max_chunk_size: number
        live_chat_min_chunk_interval_ms: number
        log_web_meta_interval_ms: number
        max_duration_to_consider_mouseover_as_hover: number
        max_prefetch_window_sec_for_livestream_optimization: number
        min_mouse_still_duration: number
        min_prefetch_offset_sec_for_livestream_optimization: number
        minimum_duration_to_consider_mouseover_as_hover: number
        mweb_history_manager_cache_size: number
        network_polling_interval: number
        pacf_logging_delay_milliseconds_through_ybfe_tv: number
        pbj_navigate_limit: number
        polymer_log_prop_change_observer_percent: number
        post_type_icons_rearrange: number
        prefetch_comments_ms_after_video: number
        prefetch_coordinator_command_timeout_ms: number
        prefetch_coordinator_max_inflight_requests: number
        rich_grid_true_inline_playback_trigger_delay: number
        rich_grid_watch_open_animation_duration: number
        send_config_hash_timer: number
        service_worker_push_logged_out_prompt_watches: number
        service_worker_push_prompt_cap: number
        service_worker_push_prompt_delay_microseconds: number
        shorts_inline_player_triggering_delay: number
        slow_compressions_before_abandon_count: number
        user_engagement_experiments_rate_limit_ms: number
        user_mention_suggestions_edu_impression_cap: number
        visibility_time_between_jobs_ms: number
        watch_next_pause_autoplay_lact_sec: number
        web_emulated_idle_callback_delay: number
        web_foreground_heartbeat_interval_ms: number
        web_gel_debounce_ms: number
        web_home_feed_reload_delay: number
        web_inline_player_triggering_delay: number
        web_logging_max_batch: number
        web_player_caption_language_preference_stickiness_duration: number
        web_search_inline_player_triggering_delay: number
        web_shorts_inline_playback_preview_ms: number
        web_shorts_scrubber_threshold_sec: number
        web_shorts_shelf_fixed_position: number
        web_smoothness_test_duration_ms: number
        web_smoothness_test_method: number
        yoodle_end_time_utc: number
        yoodle_start_time_utc: number
        ytidb_remake_db_retries: number
        ytidb_reopen_db_retries: number
        WebClientReleaseProcessCritical__youtube_web_client_version_override: string
        debug_forced_internalcountrycode: string
        desktop_search_bigger_thumbs_style: string
        desktop_searchbar_style: string
        embeds_web_synth_ch_headers_banned_urls_regex: string
        kevlar_duplicate_pref_cookie_domain_override: string
        kevlar_link_capturing_mode: string
        live_chat_unicode_emoji_json_url: string
        polymer_task_manager_status: string
        service_worker_push_force_notification_prompt_tag: string
        service_worker_scope: string
        web_client_version_override: string
        web_modern_subscribe_style: string
        web_shorts_expanded_overlay_type: string
        web_shorts_overlay_vertical_orientation: string
        yoodle_base_url: string
        yoodle_webp_base_url: string
        conditional_lab_ids: Array<any>
        guide_business_info_countries: Array<string>
        guide_legal_footer_enabled_countries: Array<string>
        kevlar_command_handler_command_banlist: Array<any>
        kevlar_page_service_url_prefix_carveouts: Array<any>
        web_op_signal_type_banlist: Array<any>
    }
    GAPI_HINT_PARAMS: string
    GAPI_HOST: string
    GAPI_LOCALE: string
    GL: string
    GOOGLE_FEEDBACK_PRODUCT_ID: string
    GOOGLE_FEEDBACK_PRODUCT_DATA: {
        polymer: string
        polymer2: string
        accept_language: string
    }
    HL: string
    HTML_DIR: string
    HTML_LANG: string
    INNERTUBE_API_KEY: string
    INNERTUBE_API_VERSION: string
    INNERTUBE_CLIENT_NAME: string
    INNERTUBE_CLIENT_VERSION: string
    INNERTUBE_CONTEXT: {
        client: {
            hl: string
            gl: string
            remoteHost: string
            deviceMake: string
            deviceModel: string
            visitorData: string
            userAgent: string
            clientName: string
            clientVersion: string
            osName: string
            osVersion: string
            originalUrl: string
            platform: string
            clientFormFactor: string
            configInfo: {
                appInstallData: string
            }
            userInterfaceTheme: string
            timeZone: string
            browserName: string
            browserVersion: string
            acceptHeader: string
            deviceExperimentId: string
        }
        user: {
            lockedSafetyMode: boolean
        }
        request: {
            useSsl: boolean
        }
        clickTracking: {
            clickTrackingParams: string
        }
    }
    INNERTUBE_CONTEXT_CLIENT_NAME: number
    INNERTUBE_CONTEXT_CLIENT_VERSION: string
    INNERTUBE_CONTEXT_GL: string
    INNERTUBE_CONTEXT_HL: string
    LATEST_ECATCHER_SERVICE_TRACKING_PARAMS: {
        "client.name": string
    }
    LOGGED_IN: boolean
    PAGE_BUILD_LABEL: string
    PAGE_CL: number
    scheduler: {
        useRaf: boolean
        timeout: number
    }
    SERVER_NAME: string
    SESSION_INDEX: string
    SIGNIN_URL: string
    VISITOR_DATA: string
    WEB_PLAYER_CONTEXT_CONFIGS: {
        WEB_PLAYER_CONTEXT_CONFIG_ID_KEVLAR_WATCH: {
            transparentBackground: boolean
            showMiniplayerButton: boolean
            externalFullscreen: boolean
            showMiniplayerUiWhenMinimized: boolean
            rootElementId: string
            jsUrl: string
            cssUrl: string
            contextId: string
            eventLabel: string
            contentRegion: string
            hl: string
            hostLanguage: string
            playerStyle: string
            innertubeApiKey: string
            innertubeApiVersion: string
            innertubeContextClientVersion: string
            device: {
                brand: string
                model: string
                browser: string
                browserVersion: string
                os: string
                osVersion: string
                platform: string
                interfaceName: string
                interfaceVersion: string
            }
            serializedExperimentIds: string
            serializedExperimentFlags: string
            cspNonce: string
            canaryState: string
            enableCsiLogging: boolean
            csiPageType: string
            datasyncId: string
            allowWoffleManagement: boolean
            cinematicSettingsAvailable: boolean
        }
        WEB_PLAYER_CONTEXT_CONFIG_ID_KEVLAR_CHANNEL_TRAILER: {
            rootElementId: string
            jsUrl: string
            cssUrl: string
            contextId: string
            eventLabel: string
            contentRegion: string
            hl: string
            hostLanguage: string
            playerStyle: string
            innertubeApiKey: string
            innertubeApiVersion: string
            innertubeContextClientVersion: string
            device: {
                brand: string
                model: string
                browser: string
                browserVersion: string
                os: string
                osVersion: string
                platform: string
                interfaceName: string
                interfaceVersion: string
            }
            serializedExperimentIds: string
            serializedExperimentFlags: string
            cspNonce: string
            canaryState: string
            enableCsiLogging: boolean
            csiPageType: string
            datasyncId: string
        }
        WEB_PLAYER_CONTEXT_CONFIG_ID_KEVLAR_PLAYLIST_OVERVIEW: {
            rootElementId: string
            jsUrl: string
            cssUrl: string
            contextId: string
            eventLabel: string
            contentRegion: string
            hl: string
            hostLanguage: string
            playerStyle: string
            innertubeApiKey: string
            innertubeApiVersion: string
            innertubeContextClientVersion: string
            device: {
                brand: string
                model: string
                browser: string
                browserVersion: string
                os: string
                osVersion: string
                platform: string
                interfaceName: string
                interfaceVersion: string
            }
            serializedExperimentIds: string
            serializedExperimentFlags: string
            disableSharing: boolean
            hideInfo: boolean
            disableWatchLater: boolean
            cspNonce: string
            canaryState: string
            enableCsiLogging: boolean
            csiPageType: string
            datasyncId: string
        }
        WEB_PLAYER_CONTEXT_CONFIG_ID_KEVLAR_VERTICAL_LANDING_PAGE_PROMO: {
            rootElementId: string
            jsUrl: string
            cssUrl: string
            contextId: string
            eventLabel: string
            contentRegion: string
            hl: string
            hostLanguage: string
            playerStyle: string
            innertubeApiKey: string
            innertubeApiVersion: string
            innertubeContextClientVersion: string
            controlsType: number
            disableRelatedVideos: boolean
            annotationsLoadPolicy: number
            device: {
                brand: string
                model: string
                browser: string
                browserVersion: string
                os: string
                osVersion: string
                platform: string
                interfaceName: string
                interfaceVersion: string
            }
            serializedExperimentIds: string
            serializedExperimentFlags: string
            hideInfo: boolean
            startMuted: boolean
            enableMutedAutoplay: boolean
            cspNonce: string
            canaryState: string
            enableCsiLogging: boolean
            csiPageType: string
            datasyncId: string
        }
        WEB_PLAYER_CONTEXT_CONFIG_ID_KEVLAR_SHORTS: {
            rootElementId: string
            jsUrl: string
            cssUrl: string
            contextId: string
            eventLabel: string
            contentRegion: string
            hl: string
            hostLanguage: string
            playerStyle: string
            innertubeApiKey: string
            innertubeApiVersion: string
            innertubeContextClientVersion: string
            controlsType: number
            disableKeyboardControls: boolean
            disableRelatedVideos: boolean
            annotationsLoadPolicy: number
            device: {
                brand: string
                model: string
                browser: string
                browserVersion: string
                os: string
                osVersion: string
                platform: string
                interfaceName: string
                interfaceVersion: string
            }
            serializedExperimentIds: string
            serializedExperimentFlags: string
            hideInfo: boolean
            disableFullscreen: boolean
            cspNonce: string
            canaryState: string
            enableCsiLogging: boolean
            datasyncId: string
            storeUserVolume: boolean
            disableSeek: boolean
            disablePaidContentOverlay: boolean
        }
        WEB_PLAYER_CONTEXT_CONFIG_ID_KEVLAR_SPONSORSHIPS_OFFER: {
            rootElementId: string
            jsUrl: string
            cssUrl: string
            contextId: string
            eventLabel: string
            contentRegion: string
            hl: string
            hostLanguage: string
            playerStyle: string
            innertubeApiKey: string
            innertubeApiVersion: string
            innertubeContextClientVersion: string
            disableRelatedVideos: boolean
            annotationsLoadPolicy: number
            device: {
                brand: string
                model: string
                browser: string
                browserVersion: string
                os: string
                osVersion: string
                platform: string
                interfaceName: string
                interfaceVersion: string
            }
            serializedExperimentIds: string
            serializedExperimentFlags: string
            disableFullscreen: boolean
            cspNonce: string
            canaryState: string
            datasyncId: string
        }
        WEB_PLAYER_CONTEXT_CONFIG_ID_KEVLAR_INLINE_PREVIEW: {
            rootElementId: string
            jsUrl: string
            cssUrl: string
            contextId: string
            eventLabel: string
            contentRegion: string
            hl: string
            hostLanguage: string
            playerStyle: string
            innertubeApiKey: string
            innertubeApiVersion: string
            innertubeContextClientVersion: string
            disableKeyboardControls: boolean
            device: {
                brand: string
                model: string
                browser: string
                browserVersion: string
                os: string
                osVersion: string
                platform: string
                interfaceName: string
                interfaceVersion: string
            }
            serializedExperimentIds: string
            serializedExperimentFlags: string
            disableFullscreen: boolean
            cspNonce: string
            canaryState: string
            enableCsiLogging: boolean
            csiPageType: string
            disableMdxCast: boolean
            datasyncId: string
            showInlinePreviewUi: boolean
        }
        WEB_PLAYER_CONTEXT_CONFIG_ID_HANDLES_CLAIMING: {
            rootElementId: string
            jsUrl: string
            cssUrl: string
            contextId: string
            eventLabel: string
            contentRegion: string
            hl: string
            hostLanguage: string
            playerStyle: string
            innertubeApiKey: string
            innertubeApiVersion: string
            innertubeContextClientVersion: string
            disableRelatedVideos: boolean
            device: {
                brand: string
                model: string
                browser: string
                browserVersion: string
                os: string
                osVersion: string
                platform: string
                interfaceName: string
                interfaceVersion: string
            }
            serializedExperimentIds: string
            serializedExperimentFlags: string
            cspNonce: string
            canaryState: string
            datasyncId: string
        }
    }
    XSRF_FIELD_NAME: string
    XSRF_TOKEN: string
    YPC_MB_URL: string
    YTR_FAMILY_CREATION_URL: string
    SERVER_VERSION: string
    REUSE_COMPONENTS: boolean
    STAMPER_STABLE_LIST: boolean
    DATASYNC_ID: string
    SERIALIZED_CLIENT_CONFIG_DATA: string
    LIVE_CHAT_BASE_TANGO_CONFIG: {
        apiKey: string
        channelUri: string
        clientName: string
        requiresAuthToken: boolean
        senderUri: string
        useNewTango: boolean
    }
    FEXP_EXPERIMENTS: Array<number>
    LIVE_CHAT_SEND_MESSAGE_ACTION: string
    ROOT_VE_TYPE: number
    CLIENT_PROTOCOL: string
    CLIENT_TRANSPORT: string
    TIME_CREATED_MS: number
    BUTTON_REWORK: boolean
    VALID_SESSION_TEMPDATA_DOMAINS: Array<string>
    WORKER_PERFORMANCE_URL: {
        privateDoNotAccessOrElseTrustedResourceUrlWrappedValue: string
    }
    RAW_COLD_CONFIG_GROUP: {
        configData: string
        mainAppColdConfig: {
            iosSsoSafariFsiPromoEnabled: boolean
            iosTodayWidgetEnabled: boolean
            iosEnableDynamicFontSizing: boolean
            enableMobileAutoOffline: boolean
            androidEnablePip: boolean
            postsV2: boolean
            enableDetailedNetworkStatusReporting: boolean
            hourToReportNetworkStatus: number
            networkStatusReportingWindowSecs: number
            iosSearchviewRefactoryEnabled: boolean
            ngwFlexyEnabled: boolean
            iosWatchExpandTransitionWithoutSnapshot: boolean
            androidNgwUiEnabled: boolean
            androidThumbnailMonitorEnabled: boolean
            androidThumbnailMonitorCount: number
            androidThumbnailMonitorMinimumWidth: number
            enableGhostCards: boolean
            enableInlineMuted: boolean
            ngwFlexyMaxCropRatio: number
            androidRestoreBrowseContentsFromBackStack: boolean
            searchHintExp: string
        }
    }
    RAW_HOT_CONFIG_GROUP: {
        mainAppHotConfig: {
            iosWatchExpandTransition: boolean
            iosEarlySetWatchTransition: boolean
            exposeConfigRefreshSetting: boolean
            iosEnableSearchButtonOnPlayerOverlay: boolean
            iosMinimumTooltipDurationMsecs: number
            iosFreshHomeIntervalSecs: number
            iosFreshSubscriptionsIntervalSecs: number
            iosTodayWidgetRefreshIntervalSecs: number
            iosFreshNotificationsInboxIntervalSecs: number
            signedOutNotificationsIosPrompt: boolean
            iosFreshFullRefresh: boolean
        }
        loggingHotConfig: {
            eventLoggingConfig: {
                enabled: boolean
                maxAgeHours: number
            }
        }
    }
    SERIALIZED_HOT_HASH_DATA: string
    SERIALIZED_COLD_HASH_DATA: string
    VISIBILITY_TIME_BETWEEN_JOBS_MS: number
    START_IN_THEATER_MODE: boolean
    START_IN_FULL_WINDOW_MODE: boolean
    SERVICE_WORKER_PROMPT_NOTIFICATIONS: boolean
    SBOX_LABELS: {
        SUGGESTION_DISMISS_LABEL: string
        SUGGESTION_DISMISSED_LABEL: string
    }
    ONE_PICK_URL: string
    NO_EMPTY_DATA_IMG: boolean
    MENTIONS_EDU_HELP_LINK: string
    IS_HOMEPAGE_COLD: boolean
    DEFERRED_DETACH: boolean
    RECAPTCHA_V3_SITEKEY: string
    PLAYER_JS_URL: string
    PLAYER_CSS_URL: string
    LINK_GAL_DOMAIN: string
    LINK_OIS_DOMAIN: string
    IS_TABLET: boolean
    LINK_API_KEY: string
    DISABLE_WARM_LOADS: boolean
    ZWIEBACK_PING_URLS: Array<string>
    VOZ_API_KEY: string
    STS: number
    SBOX_SETTINGS: {
        HAS_ON_SCREEN_KEYBOARD: boolean
        IS_FUSION: boolean
        IS_POLYMER: boolean
        REQUEST_DOMAIN: string
        REQUEST_LANGUAGE: string
        SEND_VISITOR_DATA: boolean
        SEARCHBOX_BEHAVIOR_EXPERIMENT: string
        SEARCHBOX_ENABLE_REFINEMENT_SUGGEST: boolean
        SEARCHBOX_TAP_TARGET_EXPERIMENT: number
        SEARCHBOX_ZERO_TYPING_SUGGEST_USE_REGULAR_SUGGEST: string
        VISITOR_DATA: string
        SEARCHBOX_HOST_OVERRIDE: string
        HIDE_REMOVE_LINK: boolean
    }
    SBOX_JS_URL: string
}>
